# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sogiza' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.0'
  pod 'SDWebImage/WebP'
  pod 'InputMask'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  # Pods for Sogiza
end
